#!/usr/bin/env python3
"""通知表のテスト用に、Claude Code 形式の JSONL を作る（境界ケースを意図して混ぜる）。"""
import json, pathlib, uuid, shutil

ROOT = pathlib.Path(__file__).parent / "logs" / "projects"
if ROOT.exists():
    shutil.rmtree(ROOT)

n = 0
def U():
    global n
    n += 1
    return f"00000000-0000-4000-8000-{n:012d}"

def user(text=None, blocks=None, ts="", sid="s1", cwd="/Users/t/dev/alpha", **kw):
    o = {"parentUuid": None, "isSidechain": False, "userType": "external", "cwd": cwd, "sessionId": sid,
         "version": "2.1.0", "gitBranch": "main", "type": "user",
         "message": {"role": "user", "content": text if text is not None else blocks},
         "uuid": U(), "timestamp": ts}
    o.update(kw)
    return o

def asst(block, mid, rid, model, usage, ts="", sid="s1", cwd="/Users/t/dev/alpha", **kw):
    o = {"parentUuid": None, "isSidechain": False, "userType": "external", "cwd": cwd, "sessionId": sid,
         "version": "2.1.0", "type": "assistant", "requestId": rid,
         "message": {"id": mid, "type": "message", "role": "assistant", "model": model,
                     "content": [block], "stop_reason": None, "usage": usage},
         "uuid": U(), "timestamp": ts}
    o.update(kw)
    return o

def usage(i, o, cw=0, cr=0, c5=None, c1=None):
    u = {"input_tokens": i, "output_tokens": o, "cache_creation_input_tokens": cw, "cache_read_input_tokens": cr}
    if c5 is not None or c1 is not None:
        u["cache_creation"] = {"ephemeral_5m_input_tokens": c5 or 0, "ephemeral_1h_input_tokens": c1 or 0}
    return u

A = []
# 1) 普通の発言（JST 23:00）
A.append(user("こんにちは、テストをお願いします", ts="2026-09-01T14:00:00.000Z"))
# 2) 1つの応答が3行に分かれる（usage は同じ値が3回）
u1 = usage(10, 100, cw=1000, cr=5000, c5=0, c1=1000)
A.append(asst({"type": "thinking", "thinking": "..."}, "msg_1", "req_1", "claude-opus-4-5-20251101", u1, ts="2026-09-01T14:00:05.000Z"))
A.append(asst({"type": "text", "text": "おっしゃる通りです。修正します。"}, "msg_1", "req_1", "claude-opus-4-5-20251101", u1, ts="2026-09-01T14:00:06.000Z"))
A.append(asst({"type": "tool_use", "id": "tu1", "name": "Bash", "input": {"command": "cd /x && npm test | tee log.txt\necho done"}}, "msg_1", "req_1", "claude-opus-4-5-20251101", u1, ts="2026-09-01T14:00:07.000Z"))
# 3) 通常の tool_result
A.append(user(blocks=[{"type": "tool_result", "tool_use_id": "tu1", "content": "ok"}], ts="2026-09-01T14:00:09.000Z"))
# 4) Esc 中断
A.append(user(blocks=[{"type": "text", "text": "[Request interrupted by user for tool use]"}], ts="2026-09-01T14:00:10.000Z"))
# 5) ツール実行の却下
A.append(user(blocks=[{"type": "tool_result", "tool_use_id": "tu2", "is_error": True, "content": "The user doesn't want to proceed with this tool use. The tool use was rejected (eg. if it was a file edit, the new_string was NOT written to the file). STOP what you are doing and wait for the user to tell you how to proceed."}], ts="2026-09-01T14:00:11.000Z"))
# 6) 深夜の発言（JST 9/2 01:30）
A.append(user("違う、そうじゃない。でもありがとう", ts="2026-09-01T16:30:00.000Z"))
# 7) スラッシュコマンド（数えない・/clear を記録）
A.append(user("<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>", ts="2026-09-01T16:31:00.000Z"))
# 8) isMeta（数えない）
A.append(user("Caveat: The messages below were generated by the user while running local commands.", ts="2026-09-01T16:31:01.000Z", isMeta=True))
# 9) Caveat（isMeta 無しでも数えない）
A.append(user("Caveat: The messages below were generated by the user while running local commands. DO NOT respond.", ts="2026-09-01T16:31:02.000Z"))
# 10) synthetic（料金に入れない）
A.append(asst({"type": "text", "text": "API Error"}, "msg_syn", "req_syn", "<synthetic>", usage(0, 0), ts="2026-09-01T16:31:03.000Z"))
# 11) サブエージェント側の文章（口ぐせは数えない・usage は数える）
A.append(asst({"type": "text", "text": "申し訳ありません"}, "msg_side", "req_side", "claude-haiku-4-5-20251001", usage(200, 50, cw=300, cr=0), ts="2026-09-01T16:32:00.000Z", isSidechain=True))
# 12) サブエージェントへの指示（発言に数えない）
A.append(user("サブエージェントへの指示です", ts="2026-09-01T16:32:01.000Z", isSidechain=True))
# 13) Edit / Write
A.append(asst({"type": "tool_use", "id": "tu3", "name": "Edit", "input": {"file_path": "/x/src/app.ts", "old_string": "a", "new_string": "b"}}, "msg_2", "req_2", "claude-opus-4-5-20251101", usage(5, 40, cw=0, cr=6000), ts="2026-09-01T16:33:00.000Z"))
A.append(asst({"type": "tool_use", "id": "tu4", "name": "Write", "input": {"file_path": "/x/README.md", "content": "# x"}}, "msg_2", "req_2", "claude-opus-4-5-20251101", usage(5, 40, cw=0, cr=6000), ts="2026-09-01T16:33:01.000Z"))
# 14) 壊れた行・summary 行・空行
A.append("{this is not json \"type\":\"user\"")
A.append({"type": "summary", "summary": "テスト", "leafUuid": "x"})
A.append("")
# 15) 「続けて」
A.append(user("続けて", ts="2026-09-01T16:40:00.000Z"))
# 16) 画像つき発言
A.append(user(blocks=[{"type": "image", "source": {"type": "base64", "media_type": "image/png", "data": "AAAA"}}, {"type": "text", "text": "このエラーを見て Error: x is undefined"}], ts="2026-09-01T16:41:00.000Z"))

# 17) 会話の圧縮（要約）
A.append(user("This session is being continued from a previous conversation that ran out of context. The conversation is summarized below: ...", ts="2026-09-01T16:50:00.000Z", isCompactSummary=True))
# 18) 使用上限（synthetic）
A.append(asst({"type": "text", "text": "Claude AI usage limit reached|1756789000"}, "msg_lim", "req_lim", "<synthetic>", usage(0, 0), ts="2026-09-01T16:51:00.000Z"))

B_dups = A[:3]  # 再開したセッションに、前の行が同じ uuid で写される想定

B = []
B.extend(B_dups)
B.append(user("ultrathink いい感じにしておいて", ts="2026-09-03T01:00:00.000Z", sid="s2"))
u2 = usage(20, 300, cw=4000, cr=10000)  # cache_creation の内訳なし＝5分扱い
B.append(asst({"type": "text", "text": "申し訳ありません、完璧です！"}, "msg_3", "req_3", "claude-sonnet-4-5-20250929", u2, ts="2026-09-03T01:00:10.000Z", sid="s2"))
B.append(asst({"type": "tool_use", "id": "tu5", "name": "Read", "input": {"file_path": "/x/a.py"}}, "msg_3", "req_3", "claude-sonnet-4-5-20250929", u2, ts="2026-09-03T01:00:11.000Z", sid="s2"))
B.append(asst({"type": "tool_use", "id": "tu6", "name": "Grep", "input": {"pattern": "x"}}, "msg_4", "req_4", "claude-sonnet-4-5-20250929", usage(1, 10, cr=100), ts="2026-09-03T01:00:20.000Z", sid="s2"))
B.append(asst({"type": "tool_use", "id": "tu7", "name": "mcp__github__create_issue", "input": {}}, "msg_5", "req_5", "claude-sonnet-4-5-20250929", usage(1, 10, cr=100), ts="2026-09-03T01:00:30.000Z", sid="s2"))
B.append(asst({"type": "tool_use", "id": "tu8", "name": "Task", "input": {"prompt": "調べて"}}, "msg_6", "req_6", "claude-sonnet-4-5-20250929", usage(1, 10, cr=100), ts="2026-09-03T01:00:40.000Z", sid="s2"))

C = []
C.append(user("なんで動かないの？戻して", ts="2026-09-04T03:00:00.000Z", sid="s3", cwd="/Users/t/dev/beta"))
C.append(asst({"type": "text", "text": "You're absolutely right! 承知しました。"}, "msg_7", "req_7", "claude-sonnet-6-0", usage(100, 1000, cw=0, cr=20000), ts="2026-09-04T03:00:05.000Z", sid="s3", cwd="/Users/t/dev/beta"))
C.append(user("お願いします", ts="2026-09-05T10:00:00.000Z", sid="s3", cwd="/Users/t/dev/beta"))
C.append(asst({"type": "text", "text": "API Error: 529 {\"type\":\"error\",\"error\":{\"type\":\"overloaded_error\",\"message\":\"Overloaded\"}}"}, "msg_err", "req_err", "<synthetic>", usage(0, 0), ts="2026-09-05T09:59:00.000Z", sid="s3", cwd="/Users/t/dev/beta", isApiErrorMessage=True))
C.append(asst({"type": "tool_use", "id": "tu9", "name": "Bash", "input": {"command": "FOO=1 sudo python3 x.py; git status"}}, "msg_8", "req_8", "claude-opus-5-5", usage(3, 500, cw=2000, cr=30000, c5=500, c1=1500), ts="2026-09-05T10:00:05.000Z", sid="s3", cwd="/Users/t/dev/beta"))

def write(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in rows:
            f.write((r if isinstance(r, str) else json.dumps(r, ensure_ascii=False)) + "\n")

write(ROOT / "-Users-t-dev-alpha" / "s1.jsonl", A)
write(ROOT / "-Users-t-dev-alpha" / "s2.jsonl", B)
write(ROOT / "-Users-t-dev-beta" / "s3.jsonl", C)
# ~/.claude をまるごと落とした時に混ざる history.jsonl（形式が違う）
write(ROOT.parent / "history.jsonl", [{"display": "こんにちは", "pastedContents": {}, "timestamp": 1756700000000, "project": "/Users/t/dev/alpha"}])
print("ok", sorted(str(p.relative_to(ROOT.parent)) for p in ROOT.parent.rglob("*.jsonl")))
